### PR TITLE
Release 0.1.0

### PR DESCRIPTION
**Pull request by dorienmc**
Feature more import functions, more documentation and more tests.

### CODE REVIEW

**Comment by dorienmc** [comment]
@ChrisTerBeke Can you confirm if I can PR this?

And should I do that by:
1. Going to the dev branch (locally)
2. Do `git merge --squash release-0.1.0`
3. Check if tests succeed
4. Do `git tag -a vX.X.X -m "<message here>"`
5. Do `git push && git push --tags`
?

**Comment by ChrisTerBeke** [comment]
No, tags go into master. So if you really want to release this, merge it to master, and then merge master to development to sync up again. If you just want to get this in development so another branch can be created from it, merge the feature branch to development, do new stuff there, and keep the release branch until it's merged into master. Also, before merging into master, you wanna update the package.json version number (manually!) in the release branch.

**Comment by dorienmc** [comment]
I think merging into development is best in the case.

**Comment by ChrisTerBeke** [comment]
I'll fix some documentation (like removing the command line examples which we don't use anymore). I also see that you've added a xml to json parser within the tools. Can you also do that for the .ini files? (current the API is doing the .ini parsing or not?)

**Pull request merged**
